package no.chess.ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Jul 23 13:24:46 CEST 2018 by olj
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#BlackGamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKGAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKGAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#BlackGamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#BlackPlayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKPLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKPLAYER = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#BlackPlayer"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#ChessPiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSPIECE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#ChessPiece"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#ChessPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#ChessPosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#GamePiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GAMEPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_GAMEPIECE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#GamePiece"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#GamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_GAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#GamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Occupant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCCUPANT.<p>
     * 
     */
    public static final OWLClass CLASS_OCCUPANT = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Occupant"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Offline
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OFFLINE.<p>
     * 
     */
    public static final OWLClass CLASS_OFFLINE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Offline"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Taken
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAKEN.<p>
     * 
     */
    public static final OWLClass CLASS_TAKEN = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Taken"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Vacant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VACANT.<p>
     * 
     */
    public static final OWLClass CLASS_VACANT = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Vacant"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#WhiteGamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEGAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEGAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#WhiteGamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#WhitePlayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEPLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEPLAYER = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#WhitePlayer"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackPiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackPiece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#ChessGame
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSGAME.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSGAME = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#ChessGame"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chessboard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSBOARD.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSBOARD = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Chessboard"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Move
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOVE.<p>
     * 
     */
    public static final OWLClass CLASS_MOVE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Move"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Piece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECE.<p>
     * 
     */
    public static final OWLClass CLASS_PIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Piece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Player
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_PLAYER = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Player"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhitePiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhitePiece"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1#Entity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_ENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1#Entity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Continuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Continuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#DependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPENDENT_CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPENDENT_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#DependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Disposition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPOSITION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Disposition"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#FiatObjectPart
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FIAT_OBJECT_PART.<p>
     * 
     */
    public static final OWLClass CLASS_FIAT_OBJECT_PART = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#FiatObjectPart"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Function
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Function"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#GenericallyDependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GENERICALLY_DEPENDENT_CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_GENERICALLY_DEPENDENT_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#GenericallyDependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#IndependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDEPENDENT_CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_INDEPENDENT_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#IndependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#MaterialEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MATERIAL_ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_MATERIAL_ENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#MaterialEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Object
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECT.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Object"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECT_AGGREGATE.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECT_AGGREGATE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ObjectBoundary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECT_BOUNDARY.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECT_BOUNDARY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ObjectBoundary"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#OneDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONE_DIMENSIONAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_ONE_DIMENSIONAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#OneDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Quality
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUALITY.<p>
     * 
     */
    public static final OWLClass CLASS_QUALITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Quality"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#RealizableEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REALIZABLE_ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_REALIZABLE_ENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#RealizableEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Role
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROLE.<p>
     * 
     */
    public static final OWLClass CLASS_ROLE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Role"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Site
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITE.<p>
     * 
     */
    public static final OWLClass CLASS_SITE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Site"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#SpatialRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#SpatialRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#SpecificallyDependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIFICALLY_DEPENDENT_CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIFICALLY_DEPENDENT_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#SpecificallyDependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ThreeDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THREE_DIMENSIONAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_THREE_DIMENSIONAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ThreeDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#TwoDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWO_DIMENSIONAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_TWO_DIMENSIONAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#TwoDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ZeroDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZERO_DIMENSIONAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_ZERO_DIMENSIONAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ZeroDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ConnectedSpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONNECTED_SPATIOTEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_CONNECTED_SPATIOTEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ConnectedSpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ConnectedTemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONNECTED_TEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_CONNECTED_TEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ConnectedTemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#FiatProcessPart
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FIAT_PROCESS_PART.<p>
     * 
     */
    public static final OWLClass CLASS_FIAT_PROCESS_PART = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#FiatProcessPart"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#Occurrent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCCURRENT.<p>
     * 
     */
    public static final OWLClass CLASS_OCCURRENT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#Occurrent"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#Process
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#Process"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessAggregate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS_AGGREGATE.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS_AGGREGATE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessAggregate"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessBoundary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS_BOUNDARY.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS_BOUNDARY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessBoundary"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessualContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSUAL_CONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSUAL_CONTEXT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessualContext"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessualEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSUAL_ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSUAL_ENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessualEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ScatteredSpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCATTERED_SPATIOTEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_SCATTERED_SPATIOTEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ScatteredSpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ScatteredTemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCATTERED_TEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_SCATTERED_TEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ScatteredTemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInstant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORAL_INSTANT.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORAL_INSTANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInstant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInterval
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORAL_INTERVAL.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORAL_INTERVAL = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInterval"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalInstant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORAL_INSTANT.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORAL_INSTANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalInstant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalInterval
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORAL_INTERVAL.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORAL_INTERVAL = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalInterval"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORAL_REGION.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORAL_REGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalRegion"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#consistsOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSISTSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSISTSOF = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#consistsOf"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#hasAvailable
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASAVAILABLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASAVAILABLE = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#hasAvailable"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#isAvailablefor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISAVAILABLEFOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISAVAILABLEFOR = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#isAvailablefor"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#isVacant
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISVACANT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISVACANT = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#isVacant"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#makeMove
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAKEMOVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAKEMOVE = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#makeMove"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#moveFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOVEFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOVEFROM = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#moveFrom"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#moveTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOVETO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOVETO = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#moveTo"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#hasMovement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMOVEMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMOVEMENT = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasMovement"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOCCUPIEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOCCUPIEDBY = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isPartOf"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#occupies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OCCUPIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OCCUPIES = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#occupies"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#opponents
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OPPONENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OPPONENTS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#opponents"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#plays
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLAYS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLAYS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#plays"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasName"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasValue"));


}
