package no.chess.ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Oct 09 13:17:04 CEST 2018 by olj
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#BlackGamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKGAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKGAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#BlackGamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#BlackPlayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKPLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKPLAYER = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#BlackPlayer"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#ChessPiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSPIECE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#ChessPiece"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#ChessPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#ChessPosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#GamePiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GAMEPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_GAMEPIECE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#GamePiece"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#GamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_GAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#GamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Occupant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCCUPANT.<p>
     * 
     */
    public static final OWLClass CLASS_OCCUPANT = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Occupant"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Offline
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OFFLINE.<p>
     * 
     */
    public static final OWLClass CLASS_OFFLINE = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Offline"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Taken
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAKEN.<p>
     * 
     */
    public static final OWLClass CLASS_TAKEN = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Taken"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#Vacant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VACANT.<p>
     * 
     */
    public static final OWLClass CLASS_VACANT = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#Vacant"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#WhiteGamePosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEGAMEPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEGAMEPOSITION = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#WhiteGamePosition"));

    /* ***************************************************
     * Class http://oljontologies.org/games/chess#WhitePlayer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEPLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEPLAYER = factory.getOWLClass(IRI.create("http://oljontologies.org/games/chess#WhitePlayer"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BlackPiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLACKPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_BLACKPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BlackPiece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#BoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_BOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#BoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#ChessGame
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSGAME.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSGAME = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#ChessGame"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Chessboard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHESSBOARD.<p>
     * 
     */
    public static final OWLClass CLASS_CHESSBOARD = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Chessboard"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Move
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOVE.<p>
     * 
     */
    public static final OWLClass CLASS_MOVE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Move"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Piece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PIECE.<p>
     * 
     */
    public static final OWLClass CLASS_PIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Piece"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#Player
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_PLAYER = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#Player"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEBOARDPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEBOARDPOSITION = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhiteBoardPosition"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/ont.owl#WhitePiece
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WHITEPIECE.<p>
     * 
     */
    public static final OWLClass CLASS_WHITEPIECE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/ont.owl#WhitePiece"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1#Entity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_ENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1#Entity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#BFObject
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BFOBJECT.<p>
     * 
     */
    public static final OWLClass CLASS_BFOBJECT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#BFObject"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Continuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Continuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#DependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPENDENTCONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPENDENTCONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#DependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Disposition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISPOSITION.<p>
     * 
     */
    public static final OWLClass CLASS_DISPOSITION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Disposition"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#FiatObjectPart
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FIATOBJECTPART.<p>
     * 
     */
    public static final OWLClass CLASS_FIATOBJECTPART = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#FiatObjectPart"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Function
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Function"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#GenericallyDependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GENERICALLYDEPENDENTCONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_GENERICALLYDEPENDENTCONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#GenericallyDependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#IndependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INDEPENDENTCONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_INDEPENDENTCONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#IndependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#MaterialEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MATERIALENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_MATERIALENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#MaterialEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECTAGGREGATE.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECTAGGREGATE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ObjectAggregate"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ObjectBoundary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECTBOUNDARY.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECTBOUNDARY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ObjectBoundary"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#OneDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONEDIMENSIONALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_ONEDIMENSIONALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#OneDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Quality
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUALITY.<p>
     * 
     */
    public static final OWLClass CLASS_QUALITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Quality"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#RealizableEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REALIZABLEENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_REALIZABLEENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#RealizableEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Role
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROLE.<p>
     * 
     */
    public static final OWLClass CLASS_ROLE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Role"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#Site
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITE.<p>
     * 
     */
    public static final OWLClass CLASS_SITE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#Site"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#SpatialRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#SpatialRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#SpecificallyDependentContinuant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIFICALLYDEPENDENTCONTINUANT.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIFICALLYDEPENDENTCONTINUANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#SpecificallyDependentContinuant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ThreeDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THREEDIMENSIONALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_THREEDIMENSIONALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ThreeDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#TwoDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWODIMENSIONALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_TWODIMENSIONALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#TwoDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/snap#ZeroDimensionalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZERODIMENSIONALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_ZERODIMENSIONALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/snap#ZeroDimensionalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ConnectedSpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONNECTEDSPATIOTEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_CONNECTEDSPATIOTEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ConnectedSpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ConnectedTemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONNECTEDTEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_CONNECTEDTEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ConnectedTemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#FiatProcessPart
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FIATPROCESSPART.<p>
     * 
     */
    public static final OWLClass CLASS_FIATPROCESSPART = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#FiatProcessPart"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#Occurrent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCCURRENT.<p>
     * 
     */
    public static final OWLClass CLASS_OCCURRENT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#Occurrent"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#Process
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#Process"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessAggregate
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSAGGREGATE.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSAGGREGATE = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessAggregate"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessBoundary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSBOUNDARY.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSBOUNDARY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessBoundary"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessualContext
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSUALCONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSUALCONTEXT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessualContext"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ProcessualEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESSUALENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESSUALENTITY = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ProcessualEntity"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ScatteredSpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCATTEREDSPATIOTEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_SCATTEREDSPATIOTEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ScatteredSpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#ScatteredTemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCATTEREDTEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_SCATTEREDTEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#ScatteredTemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInstant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORALINSTANT.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORALINSTANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInstant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInterval
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORALINTERVAL.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORALINTERVAL = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalInterval"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#SpatiotemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPATIOTEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_SPATIOTEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#SpatiotemporalRegion"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalInstant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORALINSTANT.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORALINSTANT = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalInstant"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalInterval
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORALINTERVAL.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORALINTERVAL = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalInterval"));

    /* ***************************************************
     * Class http://www.ifomis.org/bfo/1.1/span#TemporalRegion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORALREGION.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORALREGION = factory.getOWLClass(IRI.create("http://www.ifomis.org/bfo/1.1/span#TemporalRegion"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#affectedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AFFECTEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AFFECTEDBY = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#affectedBy"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#makeMove
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAKEMOVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAKEMOVE = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#makeMove"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#moveFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOVEFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOVEFROM = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#moveFrom"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#moveTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOVETO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOVETO = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#moveTo"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#movementOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MOVEMENTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MOVEMENTOF = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#movementOf"));

    /* ***************************************************
     * Object Property http://oljontologies.org/games/chess#participatesIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTICIPATESIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTICIPATESIN = factory.getOWLObjectProperty(IRI.create("http://oljontologies.org/games/chess#participatesIn"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOCCUPIEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOCCUPIEDBY = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isOccupiedBy"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#isPartOf"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#occupies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OCCUPIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OCCUPIES = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#occupies"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#opponents
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OPPONENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OPPONENTS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#opponents"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/ont.owl#plays
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PLAYS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PLAYS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#plays"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasName"));

    /* ***************************************************
     * Data Property http://www.co-ode.org/ontologies/ont.owl#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.co-ode.org/ontologies/ont.owl#hasValue"));


}
